import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display, Lato } from "next/font/google";

const playfair = Playfair_Display({ 
  subsets: ["latin"],
  variable: "--font-playfair", // 👈 We create a CSS variable to use in Tailwind
  display: "swap",
});


const lato = Lato({ 
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Light, Regular, Bold
  variable: "--font-lato",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lato.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
